### ISSUE TITLE
dragulaR Install msg: ERROR: configuration failed for package ‘V8’.

### ISSUE THREAD

**Issue by sfd99** [zzawadz/dragulaR#1]
Install msg ERROR:
    configuration failed for package ‘V8’...dependency ‘V8’ is not available for package ‘dragulaR’. 

Using latest R 3.5.1, Rstudio and Ubuntu Linux 14.04 32-bit
...any suggestions?.

**Comment by zzawadz** [comment]
```
install.packages("V8")
```

It may require to install `v8` system library (`sudo apt-get install libv8-dev` in ubuntu).
